### ISSUE TITLE
Not all results shown

### ISSUE THREAD

**Issue by michaelbaisch** [alexander-heimbuch/linguee-alfred-workflow#15]
Hello,

I've noticed on a few occasions that sometimes results are omitted. Here an example where "salón" isn't shown, or the results completely omitted:

<img width="765" alt="Captura de Pantalla 2022-11-12 a las 17 20 37" src="https://user-images.githubusercontent.com/1899691/201483901-f1fa56a1-618d-409b-a65c-7334478daf06.png">
<img width="733" alt="Captura de Pantalla 2022-11-12 a las 17 19 46" src="https://user-images.githubusercontent.com/1899691/201483904-fa8255d6-c756-4973-8852-44fe17e0989e.png">

**Comment by michaelbaisch** [comment]
see https://github.com/sigito/Linguee-Workflow-for-Alfred/issues/44

**Comment by alexander-heimbuch** [comment]
Thanks for the update 👍
