### ISSUE TITLE
High Sierra Update

### ISSUE THREAD

**Issue by orkhan10** [alexander-heimbuch/linguee-alfred-workflow#2]
After the High Sierra Update, the workflow failed to fetch results. I hope someone can lend a hand. This is the one single most used thing in my Mac.

**Comment by alexander-heimbuch** [comment]
Always glad to hear that someone else is using the workflow :D As soon as I upgrade to High Sierra (should be this weekend) I will have a look.

**Comment by orkhan10** [comment]
Thank you SOOO MUCH. I did send you an email as well. :D 
When I say that it is my most used thing in my Mac, I really mean it.
Thanks again!!!

**Comment by disrupted** [comment]
same here !

**Comment by Acidham** [comment]
Same here, with High Sierra Wf throws: [ERROR: input.scriptfilter] Code 11: Exited with error code but no message

**Comment by alexander-heimbuch** [comment]
I already found the root cause, the go runtime doesn't work well with high sierra: https://github.com/golang/go/issues/22059
Will try the suggested work around later this week.

**Comment by alexander-heimbuch** [comment]
Update to go 1.9 solved the problem. It's working for me, could you verify if the updated version also works for you?

**Comment by orkhan10** [comment]
You are the best Alexander!!! I am absolutely thankful to you. For fixing the problem and in general for the workflow.

I am attaching two images, which demonstrates a character problem. It is no big deal and It doesn't bother me at all. I wouldn't wanna sound ungrateful. I am just attaching them, so that you know.

Thank you very much again! :)

![bildschirmfoto 2017-10-07 um 20 39 16](https://user-images.githubusercontent.com/18570936/31310903-0a7328b0-aba1-11e7-8f24-589af3b79b3c.jpg)
![bildschirmfoto 2017-10-07 um 20 39 20](https://user-images.githubusercontent.com/18570936/31310904-0aea2b4a-aba1-11e7-96f1-51465ee39b6c.jpg)

**Comment by orkhan10** [comment]
Oh by the way. I did send you an email as well, before you answered here. And there seems to be some sort of problem. I am attaching another image. Noch ein Bescheid für dich. :)
![bildschirmfoto 2017-10-07 um 20 51 20](https://user-images.githubusercontent.com/18570936/31310937-fc4c0f62-aba1-11e7-88f2-a06155257474.jpg)

**Comment by alexander-heimbuch** [comment]
Glad to hear, sorry this mail address should work :/ Regarding your encoding issue, this is more related to how url encoding is parsed by linguee, so there is not much I can doo :(
