### ISSUE TITLE
Use french, english, spanish, ...?

### ISSUE THREAD

**Issue by esreverse** [alexander-heimbuch/linguee-alfred-workflow#4]
What a great workflow, thanks!

Is there a way I can use other languages to translate from/to?

Kind regards,
Eric

**Comment by alexander-heimbuch** [comment]
Hey Eric,

yes I left an integration path initially open to expand the flow with more languages if somebody requests this. How would you like to access different languages? something like `ling-eo` or add another keyword for the language after the `ling` keyword?

**Comment by esreverse** [comment]
Hey Alex,

what a service! :) Currently I’m using „ge“ for GermanEnglish. If I could choose, I’d choose something like gf forGermanFrench, fi for FrenchItalian, … you get the idea. So another single keyword instead of a parameter is what I would prefer to keep it nice and short. :)


Kind regards,
Eric

**Comment by alexander-heimbuch** [comment]
Ok, will see what a nice integration will look like :)

**Comment by esreverse** [comment]
I used the LeoDict workflows which are now not anymore working due to API restrictions from LeoDict. This workflow worked like this and it was really fast and intuitive …

de Benutzung
df Haus
ef Schaden
di amore

;)

**Comment by alexander-heimbuch** [comment]
I added the requested functionality. For demo purposes german-english, german-spanish, german-french and german-italian is available. You can easily add new shortcuts if you need more, simply have a look what linguee supports.

**Comment by esreverse** [comment]
Thanks so much! This is perfect now!! Made my day, week, month(s)!

**Comment by alexander-heimbuch** [comment]
Good to hear :) If you need any changes to the workflow just let me know.

**Comment by disrupted** [comment]
much appreciated indeed!

**Comment by esreverse** [comment]
Hey Alex. One more idea. It would be super convenient if it would be possible to copy the translation into the clipboard or even better paste it. Similar to the built-in dictionary functionality of Alfred. However it uses two different keywords (spell and define). So I think it's not possible to simply add a modifier key to copy/paste it instead of opening the linguee-url. But: What if there was a parameter in the settings to choose the behaviour? In 9/10 cases I need the word to paste it somewhere and not look it up furthermore ... Just an idea. :)
