### ISSUE TITLE
Add result to clipboard

### ISSUE THREAD

**Issue by alexander-heimbuch** [alexander-heimbuch/linguee-alfred-workflow#5]
Add a custom parameter to add the ability to copy to clipboard.

**Comment by alexander-heimbuch** [comment]
@esreverse created this issue to keep track :)

**Comment by alexander-heimbuch** [comment]
Please clarify what exactly should be added to clipboard :) The title or the subtitle?

**Comment by disrupted** [comment]
I'd say the subtitle containing the translation(s). if there's multiple it doesn't matter that much because then you can just paste it and choose the one you like

**Comment by alexander-heimbuch** [comment]
Added the ability to dynamical adjust alfred workflow to enable copy to clippboard (see example workflow).

**Comment by esreverse** [comment]
Doesn't work for me. When pressing Enter on an item, it opens an iOS dialog

**Comment by Schmedu** [comment]
> Added the ability to dynamical adjust alfred workflow to enable copy to clippboard (see example workflow).

Sorry for digging up this old issue, but I could not find the option in the example workflow. What are you referencing?

**Comment by alexander-heimbuch** [comment]
Maybe this helps:

<img width="1454" alt="Screenshot 2020-12-11 at 19 41 29" src="https://user-images.githubusercontent.com/7794717/101941945-05767480-3be9-11eb-994a-03d95a37e13f.png">
<img width="802" alt="Screenshot 2020-12-11 at 19 42 11" src="https://user-images.githubusercontent.com/7794717/101941958-07403800-3be9-11eb-9306-2541499cd11d.png">

**Comment by Schmedu** [comment]
Damn, did not see that. Thanks for the fast reply!
