### ISSUE TITLE
URLs do not open

### ISSUE THREAD

**Issue by eppfel** [alexander-heimbuch/linguee-alfred-workflow#6]
It seems the urls are not generated correctly.

Don't have time to look into it now.
<img width="581" alt="screen shot 2017-11-24 at 11 47 29" src="https://user-images.githubusercontent.com/1899308/33204786-4e8daa16-d10d-11e7-8d23-5a01050ef3d7.png">

I'm on Mac Sierra and just downloaded the current version in master.

**Comment by eppfel** [comment]
and awesome workflow BTW :+1:

**Comment by esreverse** [comment]
Same here. I also can't find the examples that are mentioned. :) Is there a way to revert to the old version meanwhile?

**Comment by alexander-heimbuch** [comment]
Sorry I accidentally added the `phrase` to the default behaviour. Pushed a new version that should fix this. You can find the mentioned example right in the provided workflow:
![alfred_preferences_and_linguee-alfred-workflow__git_](https://user-images.githubusercontent.com/7794717/33280206-9d1e79b2-d3a1-11e7-9f62-edda29d17eb5.png)

**Comment by esreverse** [comment]
Thanks so much! My favorite Alfred workflow now by far. :)
